### ISSUE TITLE
[Feature] Button component compiling into bulletproof button

### ISSUE THREAD

**Issue by jacobjpope** [foundation/foundation-emails#194]
Would be great if Inky compiled the buttons into Campaign Monitor's bulletproof buttons (within a div and had the sibling vml code alongside it).  I could take a stab at a PR, but it might be a bit beyond me.  I guess the hard part is inlining the class styles into the vml.

**Comment by rafibomb** [comment]
I think we are doing something like this already - @tdhartwick can you shed some light on how buttons are generated?

**Comment by jacobjpope** [comment]
When I ran the foundation build the output file only had the table html, I didn't see any VML code alongside it.  Unless I am using the wrong command or looking at the wrong output file.

**Comment by gakimball** [comment]
We haven't converted to bulletproof buttons yet, but I believe we've looked into it.

**Comment by rafibomb** [comment]
We're using another method similar to the bulletproof buttons that should work on Outlook without VML. We'll get @tdhartwick to comment on it.

**Comment by rafibomb** [comment]
Talked to @tdhartwick - We are using a version of bulletproof buttons that doesn't require the VML. It's #4 here: https://litmus.com/blog/a-guide-to-bulletproof-buttons-in-email-design It introduces an extra layer for tables but requires no VML and works on all the supported clients. 

We'd love to hear more about your experience with buttons either using border, padding or the "bulletproof" method because we're open to a better way if there is one.

**Comment by jacobjpope** [comment]
Thanks for the link @rafibomb!  Great reading, and if there is no VML required and it is giving consistent results across all the supported clients then I am happy to use it.  I only have experience with using the bulletproof buttons for the past few years because it was a solution I found and it worked across the clients I needed.  I'm going to be writing a few templates with the v2.0 RC soon so I'll get back to you with what works best.
