### ISSUE TITLE
[bug] Width not updating after setting SASS variable

### ISSUE THREAD

**Issue by allenwoot** [foundation/foundation-emails#234]
With the latest code in the v2.0 branch, when I change `$global_width` from `580px` to `600px` in scss/settings/_settings.scss, `test/visual/assets/css/foundation.css` doesn't change. I had run `npm start`, which does pick up the change.

This was working before RC 2.0.

Am I doing something wrong with the setup?

**Comment by allenwoot** [comment]
Don't think it's related, but I had to modify the backticks to single quotes to get npm build to work (it was complaining about the backtick being an illegal token).
https://github.com/zurb/foundation-emails/blob/v2.0/gulpfile.js#L138

**Comment by gakimball** [comment]
Whoops! I had some ES6 code in the Gulpfile even though it's not a Babel Gulpfile. Error didn't crop up for me because I'm on Node 5. I replaced the backticks with single quotes, so it'll work now.

As for the test suite, the commands were reworked to be consistent with [Foundation for Sites's test suite](https://github.com/zurb/foundation-sites/wiki/Testing-Guide).

To compile the documentation, run `npm start`.
To view the visual regression tests, run `npm run test:visual`.

(Once we have Sass unit tests those will be `npm run test:sass`)

Let me know if that makes sense :)

**Comment by allenwoot** [comment]
@gakimball thanks for making the change, and I also realized that I ought to have been modifying _global.scss, not _settings.scss.

**Comment by gakimball** [comment]
Yes, the settings file is just for us to drop into the external template. If you're testing the framework itself, just modify the main variables in the framework files.
