### ISSUE TITLE
non-english characters do not display correct in browsersync preview

### ISSUE THREAD

**Issue by joshvito** [foundation/foundation-emails#313]
I am using a clean/basic install of the SCSS version of Foundation for Email

The following markup

```
<columns small="12">
            <h1>いくつかのサンプルテキスト</h1>
</columns>
```

previews in the browser as 
![image](https://cloud.githubusercontent.com/assets/1249866/14175112/e8b0b688-f716-11e5-85ef-33a0bfd9a393.png)

I am using the default.html layout with the meta tag
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`

**Comment by rafibomb** [comment]
are you running `npm start` or `npm run build` when you see this happening?

**Comment by joshvito** [comment]
I am running `npm start`when this error occurs

**Comment by tdhartwick** [comment]
Strange. I just tried it out using [Slink](http://zurb.com/playground/slinky) and it seems to test out ok. It also was rendering in the CodePen. Check out the tests here:
https://litmus.com/builder/d41fb16

Going to close this down for now, since this seems to be a work around. Please reopen if the problem persists!
