### ISSUE TITLE
foundation new --framework email Fails

### ISSUE THREAD

**Issue by olliecamp** [foundation/foundation-emails#329]
**How can we reproduce this bug?**
1. run foundation new --framework email

**What did you expect to happen?**

Foundation to install

**What happened instead?**

Crashed with the following comment

Downloading the project template...There was an issue running git clone to download the Foundation for Apps template.
Make sure your computer's Git is configured properly and then try again.

**Test case**

```
foundation new --framework email
? What's the project called? (no spaces) genric2

            .
           /|     ,
      , /|/  \/| /|       Thanks for using ZURB Foundation for Email!
     /|/       |/ |       -------------------------------------------
 |___|            |___|   Let's set up a new project.
 \___|  ^^   ^^   |___/   It shouldn't take more than a minute.
     | -[O]--[O]- |
     |    ___,    |
     |    ...     |
      \__________/


Downloading the project template...There was an issue running git clone to download the Foundation for Apps template.
Make sure your computer's Git is configured properly and then try again.
```

Git is working fine. I beleive it's failing on cloning gulp 4 from git

**Comment by rockfreak** [comment]
I think it is the same error as #

**Comment by olliecamp** [comment]
Ooops didn't mean to close this.

**Comment by joshvito** [comment]
are you able to clone the github repo @https://github.com/zurb/foundation-emails-template and install via instruction on that page?

I was having problems with the foundation cli too. But this option helped be get around the issue for now.

**Comment by rafibomb** [comment]
What version of node are you running?

**Comment by joshvito** [comment]
@rafibomb,
I assume you were asking the thread creator, but I'll post my version below, in case it is helpful.

 info using npm@3.7.3
info using node@v5.4.0

**Comment by vouyoung** [comment]
Been seeing this issue on new installs of foundation lately as well

**Comment by alexanderchan** [comment]
Had the same problem, thought I had to give the project name, then realized that the value after framework is important as well.  

The command must have "emails" and not "email"

so:

foundation new --framework emails

In case anyone is interested, the framework does a lookup of the git repo.  The error is not with git, but rather that there is not a valid repository found.

![image](https://cloud.githubusercontent.com/assets/1864372/19564552/284d6c08-96a1-11e6-8a7c-3bf14ae77b77.png)

**Comment by seganaUK** [comment]
Just wanted to add my own solution in for this with regards to mac OS. I was having the exact same issue and could only find 2 solutions: 'permissions' or the missing 's' from emails. Neither of these were the issue for me. It seemed to stem from a mac OS sierra update and its affect on some command line tools. The fix for me was to download and install xcode developer tools using the following command:

`xcode-select --install`

After that, I was able to install foundation without any issue.

**Comment by DanielRuf** [comment]
> It seemed to stem from a mac OS sierra update and its affect on some command line tools. The fix for me was to download and install xcode developer tools using the following command:
> 
> xcode-select --install

Every OS upgrade requires to sign the developer agreements again, also for git.

Is the initial issue still happening?

**Comment by DanielRuf** [comment]
We are going to close this as the initial reporter did not provide enough information for us to reproduce this.

**Comment by GalvinGao** [comment]
For whom it may concern, I also ran into this issue with the `nvm` (node version manager) installed. I encountered [a `ReferenceError: primordials is not defined` issue](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node), ran `nvm use 10` (but under a nvm environment with default `node` version of `12`) and that issue seems to be fixed. But this issue now occurred.

I was able to solve this issue by completely specifying the default `node` version to `10` instead of `12`, then launch a new shell session to fully apply that.

Do `nvm alias default 10`, then close your current shell session and open a new one. Be careful that this affects your global preference of using `node` so make sure to keep that in mind.

**Comment by DanielRuf** [comment]
> For whom it may concern, I also ran into this issue with the `nvm` (node version manager) installed. I encountered [a `ReferenceError: primordials is not defined` issue](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node)

https://github.com/foundation/foundation-emails/search?q=primordials+is%3Aissue&type=issues
https://github.com/foundation/foundation-sites/search?q=primordials+is%3Aissue&type=issues

The issue here is about a completely different problem with Git. Please try to use the search next time instead of pushing old topics to the top which are not about the same issue. Thank you.
