### ISSUE TITLE
Email Footer

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#354]
Hi, 

I'm also trying to finish an email and I'm having a lot of trouble with the footer. I have icons as images and am trying to put multiple on the same line in between text. I can't seem to get them on the same line, would we be able to have a google hang out?

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
