### ISSUE TITLE
Secondary button with radius still has square border

### ISSUE THREAD

**Issue by davidhouweling** [foundation/foundation-emails#395]
**How can we reproduce this bug?**

``` html
<button href="#" class="secondary expanded radius">
  Secondary button
</button>
```

**What did you expect to happen?**
No squared border, with the button inside it being circle.

**What happened instead?**
Border is appearing square, with the button inside it being circle.

**What email clients does this happen in?**
Tested only in browser at this stage.

**Screenshot**
![image](https://cloud.githubusercontent.com/assets/9696959/14877139/9ca6395e-0d12-11e6-9f9c-bd96b3063e7d.png)

**Comment by rafibomb** [comment]
Do you see in the CSS where the difference lies? Are you able to submit a PR?

**Comment by iamsankalp** [comment]
@rafibomb @DanielZURB Got this! It's an issue with

td {
      background: $alert-color;
      **border: 2px solid $alert-color;**
    }

in **_button.scss**

It's working for primary because there's no primary class defined for button. They're by default primary.

To fix... in **node_modules>foundation-emails>scss>components>_button.scss**

change **border: 2px... under td{...} to 0px**
