### ISSUE TITLE
Hide-For-Large not working

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#413]
We have two different layouts for our social icons, and we use the class "show-for-large" and "hide-for-large" but once in litmus g-mail on chrome and firefox they are not hidden, but all the rest are. I've included screen shots
<img width="384" alt="screen shot 2016-05-02 at 4 22 36 pm" src="https://cloud.githubusercontent.com/assets/18315395/14968479/a9f0c5fc-1082-11e6-955a-dac08bdaff55.png">
<img width="443" alt="screen shot 2016-05-02 at 4 22 53 pm" src="https://cloud.githubusercontent.com/assets/18315395/14968481/a9f232d4-1082-11e6-93d1-d186d8d49c1c.png">
<img width="452" alt="screen shot 2016-05-02 at 4 23 23 pm" src="https://cloud.githubusercontent.com/assets/18315395/14968480/a9f165ca-1082-11e6-87dd-2a04d468c716.png">

**Comment by rafibomb** [comment]
`.hide-for-large` unfortunately doesn't work on gmail due to lack of media query support. it is called out in the docs:
http://foundation.zurb.com/emails/docs/visibility.html

We don't know of a work around or solution for it but would love any ideas or solutions you've found. We'll close this here. Thanks!
