### ISSUE TITLE
Emails not working

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#433]
I'm not sure what exactly happened, any time I stop watching a project, even a new one I create, when I try and watch it again I get errors. I'm not able to inline any of my projects and it seems like nothing it working. I keep getting an error that my node is not up to date, which I have checked multiple times that it is, also it says my graceful-fs module is not updated to 4.0.0 but I'm using version 4.1.0. I'm having a lot of issues and not able to fix it. My coworker has also started experiencing the same problems. I have included some of the screenshots of the terminal errors I receive.
<img width="708" alt="screen shot 2016-05-11 at 10 23 48 am" src="https://cloud.githubusercontent.com/assets/18315395/15186513/f0eb4a90-1762-11e6-8531-1e55976bb021.png">
<img width="739" alt="screen shot 2016-05-11 at 10 22 50 am" src="https://cloud.githubusercontent.com/assets/18315395/15186521/f544f532-1762-11e6-85f1-d89f9c1021a8.png">

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
