### ISSUE TITLE
Allow small-0 and large-0 classes with no padding and `display: none`

### ISSUE THREAD

**Issue by jsit** [foundation/foundation-emails#476]
Doing `column small="0"` or `column large="0"` doesn't completely remove the column at breakpoints because the left and right padding remain, as `small-0` and `large-0` are not compiled classes.

**Comment by rafibomb** [comment]
Are you looking to control the grid column gutter at different screen sizes? Perhaps the approach can look similar to Foundation for Sites: https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_gutter.scss

There is already a collapse class, and it would be best to follow a uniform approach for people using both frameworks.

Thoughts?

**Comment by rafibomb** [comment]
@jsit Does this solve your use case?

**Comment by rafibomb** [comment]
Hi @jsit Still unclear on the goals of this. We'll close this here, let us know what you're trying to accomplish and we'll go from there!

**Comment by jsit** [comment]
Thanks @rafibomb; not sure what method you're pointing out in your previous comment. Basically I want a "margin" inside the container of an email above the breakpoint, but not below it. It can be thought of as an empty column that should disappear on mobile, whose only purpose is to add whitespace. Does that make sense?

```html
  <row>
    <columns small="0" large="1"></columns>
    <columns small="12" large="10">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Perge porro; Ut aliquid scire se gaudeant? Duo Reges: constructio interrete. Aliter autem vobis placet. Graccho, eius fere, aequalí? </p>
    </columns>
    <columns small="0" large="1"></columns>
  </row>
```

**Comment by jsit** [comment]
Hi @rafibomb -- Did my explanation make sense? I still find myself adding code for `small="0"` and `large="0"` whenever I create new projects -- I find it indispensable. If I can explain something better, please let me know.

**Comment by SimonIMG** [comment]
Hi! Hope I'm not too late with a solution. We do this all the time in our eDMs.

In lieu of small=0 etc, use the offset class and show-for-large class.

```
<row>
    <columns small="12" large="10" class="large-offset-1">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Perge porro; Ut aliquid scire se gaudeant? Duo Reges: constructio interrete. Aliter autem vobis placet. Graccho, eius fere, aequalí? </p>
    </columns>
    <columns large="1" class="show-for-large">&nbsp;</columns>
</row>
```

The above makes the row stretch for the full 12 columns for mobile, but for desktop it will leave a 1 column gap either side.

The "large-offset-1" gives a 1-column gap before the content.

We then add a column with an "nbsp" on the end for the trailing 1-column gap (otherwise the content will stretch to the end of the row).

The "show-for-large" class then hides that end column for mobile. Mobile ESPs and devices (bar Gmail app) will respect the applied display:none; style, while desktop (Outlook, Gmail etc) will display the column.

**Comment by jsit** [comment]
@SimonIMG I hadn't even thought of that! That's a much more elegant solution. Thanks, I'll try it.
