### ISSUE TITLE
SCSS bug/error/conflict when using with Foundation-rails gem

### ISSUE THREAD

**Issue by PelagicDev** [foundation/foundation-emails#508]
After installing the foundation-gem, i began getting a 

`Sass::UnitConversionError at Incompatible units: 'px' and 'rem'.` error. It seems like an issue w/ line 52 in the `_settings.scss` file: `$global-width: rem-calc(1200);`.

**How can we reproduce this bug?**
Generate a new Rails 5 application and add the foundation-rails & foundation-emails gems to the gemfile. Add the `@import 'foundation-emails';` line to the scss.rb file and launch the app.

--> [Here is a fresh rails app setup to reproduce this error](https://github.com/jegodwin/foundation-emails-scss-issue)

**Comment by rafibomb** [comment]
Sounds like the app is pulling the settings from the Foundation for Sites settings file. Are you using both frameworks?

**Comment by zokioki** [comment]
Just updated the README's gem section - thanks for pointing this out @jegodwin!.

You're seeing this error because `foundation-rails` uses rems, while `foundation-emails` uses only pixels for email styling. So, instead of importing `foundation-emails` into your `application.scss`, you should have it included in a separate manifest file, dedicated to your emails.

**Comment by PelagicDev** [comment]
Works for me. Thanks for clearing that up @zokioki!

**Comment by AbdullahAs** [comment]
I'm using the same configuration above in a rails app. However, the foundation-emails overrides many of the settings I placed in the _settings.scss file of foundation-sites which leads to many broken site views.

Trying to import the settings file into foundation_emails.scss file wont work since the px vs rem issue. 

My application.scss file looks like this:

`........
*= require_tree .
*/

@import "foundation_and_overrides";

/*
*= require_self
*/`

I thought as a work around to modify the css file of emails but it require lots of work, any work around here?

### UPDATE

I've managed to fix this temporary by stubbing the file from the tree

**Comment by PelagicDev** [comment]
Most likely, @AbdullahAs, the `require_tree` line is what it causing the error for you.

So, first off, remove the `require_tree` & `require_self` bits and just reference each file individually only using the SCSS syntax like so: `@import 'foundation_and_overrides';` for each of your SCSS files. That alone will save you some debugging time down the road.

Also, you need to have a separate file for your emails manifest. So, create a new SCSS file called something like `application_emails.scss`, and treat that as your `application.scss` file for ONLY your email styling, and then include the `@import 'foundation-emails';` line in that file.
