### ISSUE TITLE
Fluid Width Header Example Doesn't Work on Mobile

### ISSUE THREAD

**Issue by benlilley** [foundation/foundation-emails#523]
I'm trying to get a simple full width header with a logo in it working. I followed the example found at the [bottom of this page](http://foundation.zurb.com/emails/docs/wrapper.html) but when I view it on mobile there is a width of 580px set on the `.container` tag which causes the layout to break on mobile:

![screen shot 2016-07-12 at 5 30 12 pm](https://cloud.githubusercontent.com/assets/167721/16756088/c091d0a6-4856-11e6-8cf7-e3af680d694e.png)

I'm aware that browser responsive tool isn't a fully accurate test of mobile rendering but I see the same result when sent out via Campaign Monitor to my iPhone and other clients. Instead of the current behaviour I would expect to see the wrapper/container shrink to 100% width on mobile and fit the image inside.

To replicate this create a new project and put this inside the template:

``` html
<wrapper class="header">
    <spacer size="16"></spacer>
    <center>
        <container class="header-container">
            <row class="collapse">
                <columns small="6" valign="middle">
                    <img src="http://placehold.it/200x50/663399">
                </columns>
                <columns small="6" valign="middle">
                    <p class="text-right">BASIC</p>
                </columns>
            </row>
        </container>
    </center>
    <spacer size="16"></spacer>
</wrapper>
```

Now open the built template on a small screen and you should see the fixed width on the container.

**Comment by rafibomb** [comment]
Looks like this was updated the other day in the develop branch. You can check it out here: https://github.com/zurb/foundation-emails/commit/d291e05d419edb8454d0e9b26cf92f9cd3a65286

It's actually much simpler now and tested perfect across all clients.

**Comment by benlilley** [comment]
I think I might be missing something @rafibomb? That example still doesn't render correctly on mobile clients? I still get a table with .container class and a fixed width of 580px, which breaks the layout...

**Comment by markadrake** [comment]
Yeah sorry but I feel like a lot of issues in this repo are being closed prematurely. There are multiple people opening up issues with images - we just had a problem with full width images in Outlook in a 12 column row for example. But even that one was closed before a solution was provided. 

Rafibomb - what was the solution to this issue and could you please document it here so that other people coming to this page can benefit from it. If it's not resolved and not in the latest major version could you please reconsider opening it until it is fully resolved? It's terribly confusing how this is managed right now.
