### ISSUE TITLE
Foundation template Litmus task crashes due to AWS

### ISSUE THREAD

**Issue by lbineau** [foundation/foundation-emails#588]
If I don't want to use AWS, the Litmus (delete the part in config.json) it crashes.

``` bash
InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
```

What would be nice is to test the existance of AWS in the config and launch or not the task according to it.

**Comment by davehoran** [comment]
So I can test my understanding here: you you deleted the AWS portion of the config.json and it crashes?

**Comment by lbineau** [comment]
Yes that's the problem.

**Comment by cossssmin** [comment]
AWS is the only supported (and _required_) 'storage driver' for the Litmus tests functionality to work, so of course it will crash.

However, this brings up a valid point. It might be useful to have the ability to use, say, an FTP gulp task that uploads to your server, instead of AWS. Just as there's also Email on Acid, which is cheaper (and less popular, but still great) than Litmus :)

**Comment by lbineau** [comment]
Well in my opinion if you don't have any images in your email you want to be able to deactivate AWS. That's why I agree with the "bug" flag. For now I just comment aws subtask in the litmus gulp task.
That would be awesome to have a FTP task !

**Comment by DanielRuf** [comment]
> For now I just comment aws subtask in the litmus gulp task.

This is the recommended solution for now. The gulpfile provides only a basic standard setup. You can extend and change it as you need.
