### ISSUE TITLE
Trim down dependencies. It's overkill!

### ISSUE THREAD

**Issue by retan** [foundation/foundation-emails#596]
After creating a new project, there is node_modules folder with:
- 111 016 files
- 10 403 folders
- total size of 294 MB

I don't have to tell you that the installation took a while.
This is ridiculous. 
All the dependencies installed their dependencies, which installed their dependencies...
A path example:
[project root]\node_modules\babel-core\node_modules\babel-generator\node_modules\detect-indent\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan\

Running on Windows 10 64bit Pro, npm: '2.15.8', node: '4.4.7',

**Comment by cossssmin** [comment]
Hello, and welcome to developing with Node and NPM :)

Jokes aside, this isn't an issue with the framework itself. It's something inherent to NPM, and how dependency management is designed around it. 

I do agree it's best to use packages with minimal to no dependencies, as much as possible. For anything else, it should be opt-in (see https://github.com/zurb/foundation-emails/issues/425). But in many cases, like the BabelJS compiler you've mentioned, there's no way around it.

I guess you never ran into NPM issues where you had to remove the entire `node_modules` folder and re-install dependencies? If not, you will, and that's... fun :(

Also, since you're on Windows, take a look at the `imagemin` module, to see a really long dependency chain. You won't even be able to delete that folder as usual in Windows (path too long), unless you use something like rimraf (deleting the folder from Sublime Text also works).

**Comment by retan** [comment]
I'm aware that it's the nature of node and npm and I'm aware it's not a simple thing to optimize.
I got frustrated after setting up a test project and trying to delete it from my hdd. It took me about half an hour and about 20 manual steps (the paths were to long for Windows to remove, so Ctrl+X, Ctrl+V x 20). Blame me for not using a shell command for a simple file removal in the first place 😆 .

This is not the first complex package I'm using (though I'm not a full time developer either). I've run into similar problems before but not with this degree.

What bothers me most in this case is that foundation emails is meant to do a pretty simple task, there's just a handful of settings and components to use and despite that this package is a mammoth.

There is a way around it. Don't use dev dependencies in the distributed package - use them for your own development only and compile the necessary staff into your own code.

Just to be clear - I admit I was pretty angry after wasting half an hour on moving and deleting files but I don't try to be rude or blame anybody. The bottom line is that this package could use some serious optimization (and docs should be updated by the way, but that's a different story).

**Comment by phil-lgr** [comment]
@retan you can use `rimraf` utility for that (https://www.npmjs.com/package/rimraf)

**Comment by DanielRuf** [comment]
Try updating to Node.js 8 and npm 5. This should dedupe it a bit.
