### ISSUE TITLE
partials and pages rendering outside of HTML tags?

### ISSUE THREAD

**Issue by becandoo** [foundation/foundation-emails#616]
**How can we reproduce this bug?**
1. Installed foundation for emails on Windows 10 use foundation-cli
2. Used npm start to view in browser. Initially everything works as expected.
3. Created partial called header.html
4. Then I noticed the header partial was response but index.html page content was not. I looked at the source in google Chrome and it seems that the only thing being inserted into {{> body}} is the header, everything else is placed outside of the parent tags (see below) 

Write out the HTML (or Inky code) that causes the issue.

```
    <table class="body">
      <tr>
        <td class="center" align="center" valign="top">
          <center>
            {{!-- Pages you create in the src/pages/ folder are inserted here when the flattened emails are created. --}}
            {{> body}} <----- I expect all pages/partials would be placed here, is this incorrect thinking on my part?
          </center>
        </td>
      </tr>
    </table>
```
Instead, the header partial is inserted between the <center> tags (as expected), but everything else is inserted after the:

```
<table class="body"></table>
```

**What did you expect to happen?**
I expected all partials and pages to be rendered inside of the {{> body}}
**What happened instead?**
The header partial rendered inside of the {{> body}}, however, the page content from index.html did not.
**What email clients does this happen in?**
Chrome Browser.

**Comment by rafibomb** [comment]
Not sure what the issue is here. Where did you add the header partial? I don't see it in your markup?

The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
