### ISSUE TITLE
Inliner PHP-Code is being destroyed

### ISSUE THREAD

**Issue by Tilogorn** [foundation/foundation-emails#666]
Inliner input:
```
<p><?php echo $myObj->myMethod(); ?></p>
```
Inliner output:

```
[...]
<p>myMethod(); ?&gt;</p>
[...]
```

I understand that PHP-Code in HTML may not be a requirement that the Inliner has to handle, but a little hint in the docs would be nice. I think it's a common use case that emails are generated dynamically.

Nevertheless it would be very nice to have that functionality (e.g. let the inliner ignore everything between `<?` and `?>`). It would save me the intermediate step to replace `Lorem Ipsum` with the PHP `echo`s for every optical template iteration.

**Workaround for desperate PHP developers:**

Instead of putting PHP directly in the HTML-Code:
```
Hello <?php echo $recipient['name']; ?>
```

use this:
```
Hello -recipient_name-
```

and substitute it in the send-process
```
$html_email = str_replace('-recipient_name-', $recipient['name'], $html_email);
```

**Comment by joeworkman** [comment]
I would use Mustache or Handlebars. Its much more powerful and super easy to use.

**Comment by davehoran** [comment]
If the goal is to have the PHP code in the processed output file, then you could also write a small Helper file that would allow you to do this. Many email system have their own variables and methods of inclusion. I ran into this with my provider. They also used Handlebars-formatted variables, so that really confused things. A Helper function allowed me to use Panini to generate the variables needed in the output file, without choking the compilation process.

**Comment by DanielRuf** [comment]
Closing as this depends on the project - we recommend using the Foundation Emails template and the `raw` tags or handlebars and replace the needed parts.
