### ISSUE TITLE
Issue with Gmail on smartphones 

### ISSUE THREAD

**Issue by AmeliePoulain92** [foundation/foundation-emails#668]
![image](https://cloud.githubusercontent.com/assets/13813409/21243926/dd0a16d8-c323-11e6-96df-c0376f2c43c3.png)

There's no paddings on this resolution of screen. when we check on desktop it works fine, but on smartphones, especially on Iphone6s/Android it looks like this. without paddings.

**Comment by davehoran** [comment]
Do you have access to something like Litmus.com so you run this code
against a number of clients? This might help you find a pattern.

On Dec 15, 2016 5:10 PM, "Arthur" <notifications@github.com> wrote:

[image: image]
<https://cloud.githubusercontent.com/assets/13813409/21243926/dd0a16d8-c323-11e6-96df-c0376f2c43c3.png>

There's no paddings on this resolution of screen. when we check on desktop
it works fine, but on smartphones, especially on Iphone6s/Android it looks
like this. without paddings.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zurb/foundation-emails/issues/668>, or mute the thread

**Comment by AmeliePoulain92** [comment]
Thanks for your reply. I've already use mailchimp. I just want to know, is it a gmail problem and what i need to do in this case, please suggest

**Comment by AmeliePoulain92** [comment]
so what? i've resolved the problem. And you couldn't help anyway?

**Comment by markadrake** [comment]
@AmeliePoulain92 please slow down just a bit. I understand your frustrated with how `gmail` is rendering your e-mail. Hopefully we can resolve that. 

**Did you resolve this already?** 

If so could you please share how you fixed your padding issue? I'm sure that it will help other people who'll find themselves here down the road. 

Then the issue can be closed.

**If you didn't solve this already...**

Please give us more to replicate your issue. We would need HTML, CSS, possibly access to an entire mock solution to really understand what's going on. What I would suggest is to start with a simple template - does it have padding in mobile? If so use that as a reference and update your project. 

Unfortunately there are too many things that could go wrong. You could have CSS interfering, you could be misinterpreting the docs, you could have found a real error in the framework. Hard to tell unless you provide more detail.

Thanks

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
