### ISSUE TITLE
Latest node.js version breaks system?

### ISSUE THREAD

**Issue by davehoran** [foundation/foundation-emails#705]
**How can we reproduce this bug?**
Use the "n" node version manager to upgrade to version 7.4.x. Try to run standard "foundation build" command for a project. It will generate errors and fail back to command line. 

**What did you expect to happen?**

I expected the "foundation build" command to run normally and stay in watch mode.

**What happened instead?**

```
[08:08:40] Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.10.1
    at Object.<anonymous> (/Users/10189653/email-work/campaigns/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:13:11)
```
I was able to get things working again by rolling node.js back to version 6.9.5.

**What email clients does this happen in?**
-- no email client related.

**Comment by ghost** [comment]
I'm rolled back Node Js to 6.9.5 version, but it still doesn't work..
`
> gulp --production

[02:29:18] Requiring external module babel-register
[02:30:10] Using gulpfile D:\MyProjects\BF\BF17\e-mail17\gulpfile.babel.js
[02:30:10] Starting 'default'...
[02:30:10] Starting 'build'...
[02:30:10] Starting 'clean'...
[02:30:10] Finished 'clean' after 149 ms
[02:30:10] Starting 'pages'...
[02:30:23] Finished 'pages' after 13 s
[02:30:23] Starting 'sass'...
SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
[02:30:52] 'sass' errored after 29 s
[02:30:52] Error in plugin 'gulp-uncss'
Message:
    SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"

Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
[02:30:52] 'build' errored after 42 s
[02:30:52] 'default' errored after 42 s

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rapma\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-emails-template@1.0.0 build: `gulp --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-emails-template@1.0.0 build script 'gulp --production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-emails-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-emails-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-emails-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rapma\AppData\Roaming\npm-cache\_logs\2017-02-13T19_30_52_421Z-debug.log
`

**Comment by davehoran** [comment]
@rapman I'm on OSX, so I'm not sure what version you'll need to roll back to on Windows. Also, I'm not sure if the error you are getting is specifically the node version, as I got a specific error about this on my install. That said, your install does seem to be failing when the sass stuff gets processed.

**Comment by ghost** [comment]
Also, 3 days ago evrything been working great. But yeaterday i found that error. It's not only me https://github.com/zurb/foundation-emails/issues/704

**Comment by davehoran** [comment]
@rapman Interesting. You were also on a Node version much further back than the one I was using. For the COM error you are getting, I'm wondering if it's a Node version issue afterall. You tried reinstalling the foundation-cli?

**Comment by ghost** [comment]
I deleted foundation  (using "npm uninstall foundation-cli -g"), and installed  foundation again - unfortunatelly, it doesn't help... Same error. 
I'm allready missing about correct-bulding time..

**Comment by ghost** [comment]
Deafault commands "gulp", "gulp build" and other - working correctly.

**Comment by davehoran** [comment]
@rapman When you run the Gulp commands (specifically gulp build) are you getting through the inlining process?

**Comment by ghost** [comment]
Yes, it is. Actually, a have to use http://foundation.zurb.com/emails/inliner.html , for compliting my projects.
It's very inconvenient (every time adding app.css on server), but as you know my "build" function doesn't work any more... (
Here, my 'gulp build':

> [05:21:27] Requiring external module babel-register
[05:21:47] Using gulpfile D:\MyProjects\BF\BF10\e-mail10\gulpfile.babel.js
[05:21:47] Starting 'build'...
[05:21:47] Starting 'clean'...
[05:21:47] Finished 'clean' after 54 ms
[05:21:47] Starting 'pages'...
[05:21:52] Finished 'pages' after 4.76 s
[05:21:52] Starting 'sass'...
[05:22:06] Finished 'sass' after 14 s
[05:22:06] Starting 'images'...
[05:22:10] gulp-imagemin: Minified 3 images (saved 40.84 kB - 16.3%)
[05:22:10] Finished 'images' after 4.34 s
[05:22:10] Starting 'inline'...
[05:22:20] Finished 'inline' after 9.62 s
[05:22:20] Finished 'build' after 32 s

**Comment by davehoran** [comment]
When I've run into weird issues like this, I create a fresh foundation-cli project, copy in my src directory, and try again. It's almost a process of elimination to get the root of the problem. 

Also, do you use VirtualBox or Docker? Perhaps this isn't something with the foundation setup, but rather the node version or config on the Windows machine. Sorry I can't be more helpful here...

**Comment by ghost** [comment]
1. No virtual box, Docker or something.. Clean Windows 10+gulp
2. Made new project (by command: foundation new --framework emails) - same error..
i don't know what's wrong... since the moment then evrything been working good - i'm did't change in my pc anything. may be log file will help to understand what's wrong?
Sorry for my bad english(

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\rapma\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.2.0
3 info using node@v6.9.5
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle foundation-emails-template@1.0.0~prebuild: foundation-emails-template@1.0.0
6 silly lifecycle foundation-emails-template@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle foundation-emails-template@1.0.0~build: foundation-emails-template@1.0.0
8 verbose lifecycle foundation-emails-template@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle foundation-emails-template@1.0.0~build: PATH: C:\Users\rapma\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\MyProjects\BF\test\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;D:\Program Files (x86)\Skype\Phone\;D:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;D:\Program Files\AMD\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\rapma\AppData\Local\Microsoft\WindowsApps;C:\Users\rapma\AppData\Roaming\npm
10 verbose lifecycle foundation-emails-template@1.0.0~build: CWD: D:\MyProjects\BF\test
11 silly lifecycle foundation-emails-template@1.0.0~build: Args: [ '/d /s /c', 'gulp --production' ]
12 silly lifecycle foundation-emails-template@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle foundation-emails-template@1.0.0~build: Failed to exec build script
14 verbose stack Error: foundation-emails-template@1.0.0 build: `gulp --production`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\rapma\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\rapma\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid foundation-emails-template@1.0.0
16 verbose cwd D:\MyProjects\BF\test
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rapma\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.9.5
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error foundation-emails-template@1.0.0 build: `gulp --production`
23 error Exit status 1
24 error Failed at the foundation-emails-template@1.0.0 build script 'gulp --production'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the foundation-emails-template package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     gulp --production
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs foundation-emails-template
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls foundation-emails-template
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by davehoran** [comment]
Out of curiosity, create a new foundation project like you did before, but on the C: drive rather than D: drive. I'm wondering if there is an unreported permissions issue going on.

**Comment by ghost** [comment]
The same 'COM error 0x80070005'

**Comment by davehoran** [comment]
I think you need to take the log file and open a new issue for this. I'm not sure what is going on, and I'm limited as to how I can help as I'mm not working from Windows. I seems like there is an underlying issue with a Windows component that at driving the COM error.

**Comment by ghost** [comment]
Issue is already exist. https://github.com/zurb/foundation-emails/issues/704
There the man, which have the same problem

**Comment by Creativenauts** [comment]
@rapman looks like memory access error. Have you checked your event viewer logs?

**Comment by davehoran** [comment]
This appears to be a machine specific problem rather than a general Foundation/Panini problem. I'm closing the issue.

**Comment by hunzaboy** [comment]
I had updated node to latest version. After updating node-sass broke. So i did `npm rebuild node-sass`  It fixed the problem.
