### ISSUE TITLE
Reasoning for default values in variables

### ISSUE THREAD

**Issue by stevesmename** [foundation/foundation-emails#721]
Think it's important that the default values decided (especially in the settings.scss) are documented somewhere. Provide insight and education on the suggested values that are given.

For example, 
- why is the $global-width-small set to 95%?

**Comment by Creativenauts** [comment]
@stevesmename checkout the doc site which has lots of default sass variables with description.

https://foundation.zurb.com/emails/docs/global.html#sass-variables

$global-width-small
Length 95%	
Width of the container on small screens.

**Comment by IamManchanda** [comment]
@stevesmename your confusion is understandable but sass mixin and variables are documented in comments instead of for eg `docs => global.md`

You find the comments of this variable here -> https://github.com/zurb/foundation-emails/blob/develop/scss/_global.scss#L57-L59

This is then called from those Sass comments to the page like for example 
https://foundation.zurb.com/emails/docs/global.html#sass-variables

**Comment by stevesmename** [comment]
@IamManchanda and @DerekBess - thanks for suggestions. I did see the documentation on foundation.zurb.com, however was looking for more detail to answer more the "why". These questions typically come more from the designer or the Q/A process involved with clients.

I'll move this conversation into Zurb Forum. We can circle back if it's actual issue or not with code.
