### ISSUE TITLE
Optimize file size of inlined version

### ISSUE THREAD

**Issue by beningreenjam** [foundation/foundation-emails#727]
Is there a way you could prevent unnecessary style rules from being applied to certain elements.

This would go a long way to reducing the file size of inlined email templates for the benefit of being able to fit more content in without getting hit by Gmails 100KB limit. 

For example `.spacer` and `.expander` elements shouldn't need to care about text-align, colour, font-family, or font-weight. I'm sure there are probably some other areas that could be optimised too.

**Comment by ghost** [comment]
Have you tried to use UnCss? It was added to the Zurb Stack about 4 months ago. You might just need to update your version to take advantage of it.  If there are classes that are not used, it will not added them to the top of the email (which does save bloat). We use to run into this problem all the time.  However, this does not solve the problem of adding fonts styles to almost every table / td that's nested.

**Comment by DanielRuf** [comment]
I think we already use uncss in the foundation-emails-template.

See https://github.com/foundation/foundation-emails-template/blob/master/gulpfile.babel.js#L78

**Comment by elcaptain** [comment]
Hi, I'm also running into the gmail character limit some times, especially when I use many `<spacer>` elements. I agree with @beningreenjam that it has a lot of unnecessary css styling.
I don't think uncss is helpful here since it only removes unused classes from stylesheets from what i understand. The problem is that `_typography.scss` sets all these font and colour styles to all `<td>` regardless if they are used in <spacer> or not.
It would be really great to remove these unnecessary styles from the code that is generated by `<spacer>`.

**Comment by DanielRuf** [comment]
You may have to create a custom component, styles / classes or otherwise clean it up, for example with a simple gulp-replace implementation or similar.

In mosts cases spacer could be replaced by paddings / margins or by specifying the needed size and removing a few unneeded instances.

**Comment by elcaptain** [comment]
Hm, okay. I will try one of these workarounds. Thanks 👍
