### ISSUE TITLE
'hide-for-large' doesn't work on images on outlook 2007, 2010,2013,2016

### ISSUE THREAD

**Issue by matmiz** [foundation/foundation-emails#739]
Hi,
I'm using the hide-for-large class to hide sections in my email, but it doesn't seem to work on images on various versions of outlook.
I tried assigning the class to all of the image' parent elements, but it won't go away. 
Any ideas?
Thanks

**Comment by lspoor** [comment]
Can you tell us what 'parent element' you're attempting to add the class to? Some code examples would be useful

**Comment by matmiz** [comment]
Hi @lspoor , sorry you are correct. 
My code looks like this:
`<table>
   <tbody>
     <tr>
       <th>
         <img src="...">
       </th>
     </tr>
   </tbody>
</table>`

**Comment by matmiz** [comment]
Hi @lspoor , sorry you are correct. 
My code looks like this:
```
<table>
   <tbody>
     <tr>
       <th>
         <img src="...">
       </th>
     </tr>
   </tbody>
</table>
```
I tried adding the class to the img tag only, and to all of the parent elements.

**Comment by lspoor** [comment]
You can't add it to the image tag itself, as per the documentation;

> If you're using a visibility class on an image, be sure to apply it to the parent element, not to the image itself.

Try adding a `div` around the image with the visibility class, I've experienced no problems doing this.

**Comment by matmiz** [comment]
It is still not working for me. 
Only for outlook, yes? The rest of the clients are perfectly fine.

**Comment by stevesmename** [comment]
@matmiz check out #694 - think theres a good chance you're experiencing this too.

**Comment by matmiz** [comment]
@stevesmename , thanks but this is the exact opposite. 
The issue here is that the hide-for-large isn't hiding the element , where in #694 the hide-for-large is actually hiding the element.

**Comment by lspoor** [comment]
Check out the exported code and see if .hide-for-large has `display:none !important`

If it has `!important`, that is probably the reason why as Outlook doesn't respect it.

**Comment by matmiz** [comment]
I removed the `!important` , and it still didn't hide. 
I thought that outlook ignores `display:none` anyway, and this is why we use `mso-hide:all`

**Comment by staruc** [comment]
You'll need to wrap your .hide-for-large content in an MSO conditional wrapper. Anything in my markup using .hide-for-large is inside an "if not MSO" conditional wrapper. The documentation briefly refers to this http://foundation.zurb.com/emails/docs/visibility.html 


`<!--[if !mso]><!-- -->`
`<element class="hide-for-large">This won't show on large screens, or Outlook (presumed large screen).</element>`
`<!--<![endif]-->`

**Comment by matmiz** [comment]
Thanks for the help, we already decided to just make the src an empty string.

**Comment by ahubbell** [comment]
I too have been struggling with ".hide-for-large". I have 3 images that are suppose to swap if the user's on mobile. I read Corey Schaaf solution [http://foundation.zurb.com/forum/posts/46868-a-fix-for-hidingshowing-content-depending-on-small-or-large-devices](http://foundation.zurb.com/forum/posts/46868-a-fix-for-hidingshowing-content-depending-on-small-or-large-devices), but with my deadline passing me by did not want to rebuild the entire email. 
I understod the point that you can't put the class directly on the img tag, so I decided to use the ".callout" class. Styling it to match the main email (no border, same color, etc) and put the img tag in that. 
This worked to a point, but as has been pointed out ".hide-for-large" fails once the email has been inlined. In development it woks like a charm.

That was when I came across  ARTUR3X post on Github - "Visibility Classes .hide-for-large class Workarround #734 [](https://github.com/zurb/foundation-emails/issues/734)" I was delighted and gave it a try (Thank you ARTUR3X).

ARTUR3X proposed:
_"**I have found out that removing the !important generated in the display:none!important after i run the inline via (np run build) it. and saving that inliner it makes the hide for large work perfectly.**"_

So after I inlined and minifiyed the email I just did a search and replace "**display:none!important**" with "**display:none**". Two were found and replaced and the email preformed as expected. I suspect since the ".show-for-large" is the default view making it "!important" overrides the ".hide-for-large" class after inlining since css give different weights to inline vs class styles (or something along those lines). Corey can you see any potential issues with this approach? Attached is some code snippets from my project if you care to see further.
[Code snippet examples.pdf](https://github.com/zurb/foundation-emails/files/922754/Code.snippet.examples.pdf)
