### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by Vilsafur** [foundation/foundation-emails#944]
Is this deposit still maintained?

The last commit more than 2 years ago, and the last valid pull-request is from October 2017.

**Comment by lkraav** [comment]
Your finding probably answers itself.

I noticed the same thing and did not dare to adopt this project for my solution base.

**Comment by mrmckeb** [comment]
This is a great project, it would be a shame if it was no longer supported. I've always used Ink, and had great respect for the project and team.

It looks like https://mjml.io/ is well supported if anyone is looking for an alternative, and I've heard good things from teams in my company.

**Comment by st-h** [comment]
There have been quite a few similar issues and comments in the past weeks/months. To sum it up, what I understood:
The project is still used actively by the maintainers and fixed in case there is a serious issue. Regarding the open issues / PRs, people are welcome to review and help get things sorted out.
I just noticed there also is #938, which has been created by one of the maintainers. I think the main issue is that their time currently is very limited.

Just as a side note, I switched from mjml to this project because I encountered too many limitations using mjml (especially regarding templating support), so you might want to take those recommendations with a grain of salt...

**Comment by Vilsafur** [comment]
Thanks for your replies.

So, if I've understand, I can use Foundation-emails for my project. But no update are planned for now and just the criticals bugs are corrected.

**Comment by shnizmuffin** [comment]
Should a critical bug arise, I doubt it would be corrected.

**Comment by Vilsafur** [comment]
😢 this reply don't help me to know if I could adopt the framework

**Comment by st-h** [comment]
I did a quick search for a few references to the information from my previous post. 
I think most information regarding current state of this repo can be found within  https://github.com/zurb/foundation-emails/issues/893
And there is an issue where I asked how we could move forward with the open PRs https://github.com/zurb/foundation-emails/issues/860

But to quote from the first issue the main problem seems to be this one:

> there is just a lack of active contributors and maintainers (like in many opensource projects).

so, it very likely is not dead or unmaintained, but available resources are currently an issue

sorry @shnizmuffin , I don't think speculations are of any help here...

However, if we find something that does not work, are able to provide a PR and get that merged, we are all good. We just need to make that happen somehow 😬

**Comment by shnizmuffin** [comment]
@st-h, [It's not speculation](https://github.com/zurb/foundation-emails/graphs/code-frequency). It would be irresponsible to tell someone, "yeah, this project is still in active development," when it's very obviously not. Without an active member with the authority to approve and merge PRs, this project is a zombie.

@Vilsafur, if you're uncomfortable working through NPM errors, don't adopt this framework. If you are uncomfortable cobbling together a working framework from the myriad of PRs in this repo, don't adopt this framework. Once you get it working and you understand it's quirks, it's fine.

MJML seems like the next best option, but it has a completely different philosophy behind it. It is limited in scope and rigid in design - which is completely fine for some applications and a complete non-starter in others.

**Unless you have the confidence and ability to maintain your own fork, you should not adopt this framework.**

**Comment by ghost** [comment]
I have been using foundation for Emails 2.0 since 2015.  I use to be in regular contact with Rafi (one of the main guys who works on this code base and foundation for sites. As I understand it, there was alot of turnover at Zurb and people I was in regular contact with no longer work there. 

I use to be very active on the Forums and helped lots of people with Foundation for Emails 2.0 but as a result of them doing nothing to fix the issues with spam bots;  users (like myself) quit contributing because legitimate users would be marked as spam. Kind of frustrating answering all those questions only to have your post marked as spam. Some answers that were very lengthy sometimes took hours to write. 

With that said, I still use the Framework. And while there have been no additions or official releases for quite sometime it's still one of the better options for producing emails. I even took the class that they offered as I have a team of 4 individuals who use this product every day and crank out over 350 emails per year.  

I've customized my solution a lot and taken advantage of items that were on git.  But not even seeing any of the moderators post on this tread is very disheartening. I'm not saying you should find an alternative solution, I'm saying you will get very little help from the people who wrote the code base and it's mainly up to die hards to keep it alive. 

https://foundation.zurb.com/forum/6934-corey-schaaf

**Comment by DanielRuf** [comment]
Hi,

sorry but most of us o not get any notifications about new issues or comments.

**Comment by iRyusa** [comment]
@st-h 

> Just as a side note, I switched from mjml to this project because I encountered too many limitations using mjml (especially regarding templating support)

👋Would be happy to discuss about those limitations ? (You can come on mjml slack if you want?)

**Comment by st-h** [comment]
@iRyusa Among other things I had to create a daily digest which is composed of various events. In the end the requirement was to create a handlebars based template (using Mjml or foundation) which then can be compiled by the backend server (using handlebars) and then sent out via email. If I remember correctly back then custom components were not working or not finished - at least there were a few major issues. At last it turned out to be a major pain to create such a complex template using Mjml. This was probably a year (maybe 2) ago. Sorry, just a little too long ago to provide a lot of details. And I can't say anything about recent development though. I'll be happy to give it another try whenever I can put enough time aside.

@DanielRuf that sounds like a real major issue, if the maintainers are not even able to get notified about what is going on within the repo. Is there any way to fix that? As much as I personally like foundation-emails, and I am aware that we do not have a lot of alternative frameworks out there, but by now I am really getting worried as well.

**Comment by DanielRuf** [comment]
> @DanielRuf that sounds like a real major issue, if the maintainers are not even able to get notified about what is going on within the repo

I am not a maintainer in this repo but foundation-sites. This is not group wide.

**Comment by Vilsafur** [comment]
@shnizmuffin, I'm not uncomfortable working through NPM errors, but I can't use an abandoned repo in production. And I don't think fork this repo for upgrade only for myself is a good think.

@DanielRuf So, who is the maintainer, can he come and take care of it?

**Comment by DanielRuf** [comment]
It is not abandoned, life is just more important for most of us and we are volunteers who do this in our spare time.

**Comment by ghost** [comment]
@DanielRuf I apologize for this question - but you don't work at Zurb if I understand correctly? You are a contributor of Zurb and not the original programmers.  As such, for people to use this confidently (or start to use this in production as I have been using it in production for over 3 years now) there would need to be more support for it.  The problem that I have is that no one from Zurb is saying yes it is still a Framework maintained by the people who built it or NO it is not something we maintain anymore and let users make pull and push request.  

According to Zurb's website, they still accept money for their training courses (but there are all just videos) https://zurb.com/university/responsive-emails-foundation?utm_campaign=Footer+Upsell&utm_content=Footer&utm_medium=Docs&utm_source=Foundation+Docs which I find odd being that there has been no major activity on this repo for quite some time.  

I don't think @Vilsafur is accusing you of anything, I think his understanding (and correct me if I'm wrong) is that you are one of the programmers from ZURB.  That does not seem to be the case.  No one is blaming you for having a life especially if you're a volunteer, but if you were an employee of ZURB and telling us "it's not abandoned, life is just more important for most of us" is really a turn off when it comes to using a framework that many of us rely on to keep our own clients happy.

**Comment by DanielRuf** [comment]
In general you are right but keep in mind: this is opensource, see the MIT license ;-)

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.

I'll ask the other Yetinauts / Foundation Sites contributors and maintainers how we can proceed here with Foundation Emails as most of us have no push permissions here.

**Comment by ghost** [comment]
Thanks @DanielRuf !

**Comment by st-h** [comment]
@DanielRuf I think the issue most people are having is that
- PRs are not getting merged
- there does not seem to be anyone around who is able (has the necessary permission) to maintain this repo
- the last commit > 2 years, ~50 unresolved PRs, a couple of hundred issues is treated as an indication of progress no longer being made. This is not necessarily an issue for developers themselves, but at very least for the companies who are paying the devs

I am aware that there are some people around who expect OSS to be a magical bullet which solves all their problems without having to spend any money or invest time in implementing, maintaining or fixing stuff. However, there are a lot of people around who are willing to dedicate to a framework, if that work inevitably will not end up as an open PR that will never get merged. So, mostly this is a chicken and egg problem imho. I think there are quite a few options to solve these issues, however almost each of them requires at least write permissions to the repo etc.

**Comment by Vilsafur** [comment]
Indeed, I am not accusing anyone, and I am also ready to contribute to the framework.
Only if my contributions can one day be taken into account.

I realize that @DanielRuf is not a member of Zurb.

As @st-h said, the problem is that the last commit was over 2 years ago, there are ~ 50 PRs pending and ~ 270 issues pending as well.

For having tested Foundation for mail and mjml, I much prefer to use foundation, but if it is not maintained any more, how do you want me to explain to my superiors that the adoption of foundation will be a perennial solution?

**Comment by burgiuk** [comment]
Duplicate #893

**Comment by DanielRuf** [comment]
Foundation Emails is still actively maintained and developed.

**Comment by st-h** [comment]
> @st-h
> 
> > Just as a side note, I switched from mjml to this project because I encountered too many limitations using mjml (especially regarding templating support)
> 
> 👋Would be happy to discuss about those limitations ? (You can come on mjml slack if you want?)

@iRyusa Just a short heads up: I finally gave mjml another try and the compiled mail templates are shorter and the rendering in the client is more consistent. Great work! so far everything improved nicely since I tried a few years ago.
